name: Build and Test on Ubuntu 22.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        cmake-version: [3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Deps
      run: |
        sudo apt-get update
        sudo apt-get install -y libeigen3-dev libyaml-cpp-dev libgtest-dev
    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_TESTING=ON
        make
        make test
